version: 2
model: 'resnet'
model_name: 'resnet50'
model_weights: 'src/data/classification/run2_2025-01-18T12:29:56_152264c353d0bb953b5642a7b812b94e8f9f9bb3/classification_weights.pth'
dataset: 'wikiart'
folder_path: './images/'
