version: 3
model_name: 'CompVis/stable-diffusion-v1-4'
style: 'early_renaissance'
data_path: 'src/data/training/early_renaissance/run6_2024-12-19T11:27:06_58c35eeb8b68b1c6e878339ee1df2393ca62626a/early_renaissance_lora_weight.pt'
prompt: 'A painting of the city munich in early renaissance style'
num_inference_steps: 50
guidance_scale: 7
r: 16