version: 2
model_name: 'CompVis/stable-diffusion-v1-4'
style: 'early_renaissance'
data_path: 'src/data/training/early_renaissance/run2_2024-12-16T19:47:46_163e34b57e2bbe9b40c561356a5537f1e2808086/early_renaissance_lora_weight.pt'
prompt: 'A painting in early renaissance style'
num_inference_steps: 50
guidance_scale: 7
r: 16