version: 20
model_name: 'CompVis/stable-diffusion-v1-4'
style: 'pop_art'
data_path: 'src/data/training/pop_art/run6_2024-12-19T11:26:12_58c35eeb8b68b1c6e878339ee1df2393ca62626a/pop_art_lora_weight.pt'
prompt: 'A painting of an orange in Style2'
num_inference_steps: 50
guidance_scale: 7
r: 16