

#- expressionismus = Style3
#- pop_art = Style2
#- early_renaissance = Style1

version: 10
general_model_name: 'CompVis/stable-diffusion-v1-4'

w1: './src/data/training/early_renaissance/run6_2024-12-19T11:27:06_58c35eeb8b68b1c6e878339ee1df2393ca62626a/early_renaissance_lora_weight.pt'
w2: './src/data/training/pop_art/run6_2024-12-19T11:26:12_58c35eeb8b68b1c6e878339ee1df2393ca62626a/pop_art_lora_weight.pt'

num_inference_steps: 30
guidance_scale: 7

blending-alpha: 0.8

prompt: "A woman in the city Style1 and Style2."
style: 'renaissance_popart'

path_save: 'src/data/merge_loras_v1/renaissance_expressionism'

