
version: 9
general_model_name: 'CompVis/stable-diffusion-v1-4'

w1: './src/data/training/early_renaissance/run6_2024-12-19T11:27:06_58c35eeb8b68b1c6e878339ee1df2393ca62626a/early_renaissance_lora_weight.pt'
w2: './src/data/training/pop_art/run6_2024-12-19T11:26:12_58c35eeb8b68b1c6e878339ee1df2393ca62626a/pop_art_lora_weight.pt'

num_inference_steps: 30
guidance_scale: 7

prompt: "A painting, Style 2."
style: 'popart_renaiss'

