version: 3
model_name: 'CompVis/stable-diffusion-v1-4'
dataset: 'wikiart'
style: 'expressionism'
prompt: 'Style3'
epochs: 50
lr: 0.00005
r: 16
dropout: 0.1
batch_size: 8
weight_decay: 0.001
patience: 15